services:
  app:
    image: ${IMAGE_NAME}
    container_name: lebvest
    env_file:
      - /opt/lebvest/.env.infrastructure
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    ports:
      - '8080:8080'
    restart: unless-stopped
