server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    username: admin
    password: secret
    url: jdbc:postgresql://localhost:5460/lebvest
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  docker:
    compose:
      enabled: false
  cloud:
    aws:
      credentials:
        access-key: minioadmin
        secret-key: minioadmin123
      s3:
        path-style-access-enabled: true
        endpoint: http://localhost:9000
        region: us-east-1
  rabbitmq:
    virtual-host: /
    port: 5672
    host: localhost

  mail:
    port: 1025
    host: localhost
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enabled: false
lebvest:
  frontend-url: http://localhost:4200
  set-password-token-secret: 1b76b0e9f5f782cf5b55b8e194190c523360a91b66a0cd16c2a1344d14446aff