CREATE TYPE admin_notification_type AS ENUM (
    'NEW_APPLICATION', 'APPLICATION_ACCEPTED', 'APPLICATION_REJECTED', 'SYSTEM'
);

CREATE TABLE admin_notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      TEXT                     NOT NULL,
    content    TEXT                     NOT NULL,
    type       admin_notification_type  NOT NULL,
    read       BOOLEAN                  NOT NULL DEFAULT FALSE,
    data       JSONB,
    created_at TIMESTAMPTZ              NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_notifications_read_created
    ON admin_notifications (read, created_at DESC);

CREATE INDEX idx_admin_notifications_id_desc
    ON admin_notifications (id DESC);
